Default petition
moreonion/campaignion_starterkit_uk pull request #53
Opened 2021-06-01 12:48 UTC by CharlieSeagull

2021-06-17 10:08 UTC, katzmo requested changes

2021-06-17 10:08 UTC, katzmo commented on modules/campaignion_petition/campaignion_petition_templates/campaignion_petition_templates.features.uuid_node.inc
> -    'progressbar_page_number' => 1,
This needs to stay on.

2021-06-17 11:00 UTC, katzmo approved these changes

2021-06-29 14:35 UTC, torotil approved these changes

2021-07-20 15:24 UTC, merged