[Match-to-target] Add content type, copy from custom module.
moreonion/campaignion_starterkit_uk pull request #63
Opened 2022-10-03 19:36 UTC by katomat

Add match to target content type.

2022-10-07 08:25 UTC, torotil commented
This needs a migration path for existing sites with that extension.

2022-10-10 13:14 UTC, torotil requested changes

2022-10-10 13:14 UTC, torotil commented on modules/campaignion_match_to_target_type/src/ChannelEmailNoSend.php
> +}
This class should better be put into the [campaignion](https://github.com/moreonion/campaignion) project. Perhaps in the email to target module. Then we don’t need to copy&paste it into all profiles.

2022-10-13 11:03 UTC, torotil approved these changes
I’ve commented on one tiny string issue, but otherwise I think it’s fine.

2022-10-13 11:03 UTC, torotil commented on modules/campaignion_match_to_target_type/campaignion_match_to_target_type.features.field_instance.inc
> +    'description' => 'Add a large main image or a video to your match_to_target action.',
I don’t think `match_to_target` is suitable for UI strings.

2022-10-13 13:01 UTC, katomat commented on modules/campaignion_match_to_target_type/campaignion_match_to_target_type.features.field_instance.inc
> +    'description' => 'Add a large main image or a video to your match_to_target action.',
I agree.  I decided to go with: "Add a large main image or a video to your action.".
e2t has "Add a large main image or a video to your email_to_target."

2022-11-10 11:41 UTC, merged